### ISSUE TITLE
Add README indicating how to deploy these policy files

### ISSUE THREAD

**Issue by gene1wood** [iocoop/policies#3]
@garyp Can you add a README indicating how to deploy these policy files so they're live on the site?

**Comment by garyp** [comment]
@gene1wood It's been ages since I deployed an update to the policies, but I think we do it by redeploying `django-iocoop` using the instructions at https://github.com/iocoop/django-iocoop/blob/master/README.md#to-deploy.

I thought we had a shortcut method when we only have policy updates to deploy, but I can't remember what it was now (if there even was one).

**Comment by garyp** [comment]
FYI I just deployed the latest copies of the policy files (looks like we had never published the edits that had been made to the policies over the last couple years). Steps involved were:

* Check out `django-iocoop` git repo
* `pushd iocoop/static/policies/`
* `git pull`
* `popd`
* `git commit -m "Update to latest policies" iocoop/static/policies/`
* Then deploy `django-iocoop` using the normal deploy instructions
